sudo: required
dist: xenial
language: node_js

install: true

git:
  depth: false
  quiet: true

stages:
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: tests
      name: "Code Style Check"
      node_js: 11.0.0
      before_script:
        - npm install
      script: npm run lint

notifications:
  email: false