name: End-to-end tests
on: [push]

jobs:
  cypress-e2e-headless:
    name: Cypress e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
        browser: ["firefox", "chrome"]

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Clone backend
        run: |
          git clone --branch feature/multistage-build https://github.com/CSCfi/beacon-network

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./beacnon-network/Dockerfile
          tags: localhost:5000/beacon-network:latest
          cache-from: localhost:5000/beacon-network:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
     
      - name: Run beacon-network container
        run: |
          docker-compose -f beacon-network/docker-compose-test.yml up -d
          sleep 30 

      - name: Set up for tests
        run: ./beacon-network/tests/test_files/add_fixtures.sh

      - name: Run Frontend
        env: 
          VUE_APP_AGGREGATOR_URL: http://0.0.0.0:5050/
          VUE_APP_REGISTRY_URL: http://0.0.0.0:8080/
          VUE_APP_DEVELOPMENT: true
        run: |
          npm install
          npm run build
          nohup python -m http.server 8081 --d ./dist &
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
