name: End-to-end tests
on: [push]

jobs:
  cypress-e2e-headless:
    name: Cypress e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
        browser: ["firefox", "chrome"]

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Clone backend
        uses: actions/checkout@v2
        with:
          repository: 'CSCfi/beacon-network'
          ref: 'dev'
          path: beacon-network

      - name: Build Backend
        uses: docker/build-push-action@v2
        with:
          context: ./beacon-network
          push: true
          file: ./beacon-network/Dockerfile
          tags: localhost:5000/beacon-network:latest
          cache-from: localhost:5000/beacon-network:latest
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Clone beacon 2
        uses: actions/checkout@v2
        with:
          repository: 'CSCfi/beacon-2.x'
          ref: 'test'
          path: beacon2

      - name: Create LFS file list
        run: |
          cd beacon2
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: beacon2/.git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - name: Git LFS Pull
        run: |
          cd beacon2
          git lfs pull
      
      - name: Run beacon 2
        run: |
          cd beacon2/deploy
          docker network create beacon-network_apps
          docker-compose up -d db
          sleep 30
          docker-compose up -d
          sleep 30
          
      - name: Set up beacon-network
        run: |
          cd beacon-network
          docker-compose -f docker-compose-test.yml up -d
          sleep 30
          ./tests/test_files/add_fixtures.sh

      - name: Build Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            "VUE_APP_AGGREGATOR_URL=http://localhost:5054/"
            "VUE_APP_REGISTRY_URL=http://localhost:8083/"
            "VUE_APP_DEVELOPMENT=true"
          push: true
          file: ./Dockerfile
          tags: localhost:5000/beacon-network-ui:latest
          cache-from: localhost:5000/beacon-network-ui:latest
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Run Frontend
        run: |
          docker-compose -f docker-compose-test.yml up -d
          sleep 30
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
